/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-11 15:42:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_002dnew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Bách Khoa News</title>\r\n");
      out.write("    <!-- Icon Boostrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css\">\r\n");
      out.write("    <!-- Link Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- OWL -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!--Font Awesome --> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\" integrity=\"sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <!-- CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/shared.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/responsive.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style_homenew.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/share_homenew.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/responsive_homenew.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("       <div class=\"main\">\r\n");
      out.write("             ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        <!-- Content -->\r\n");
      out.write("        <div class=\"content category layout-container\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <h1 class=\"title\">Quả cầu pha lê khổng lồ lại rơi ở Quảng trường Thời đại</h1>\r\n");
      out.write("                <div class=\"d-flex mt-5 \">\r\n");
      out.write("                    <p class=\"category-title_name\"><strong>Mr: Name</strong></p>\r\n");
      out.write("                    <p class=\"category-title_time ms-3 text-muted\">Thứ 7, 1/1/2021 15:59(Gmt+7)</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content-hot   d-flex mt-xxl-5 \">\r\n");
      out.write("                <div class=\" col-md-8 col-lg-8 \">\r\n");
      out.write("                    <div class=\"content-main_news\">\r\n");
      out.write("                            <h2 class=\"category-heading align-justify text\">\r\n");
      out.write("                               <strong>\r\n");
      out.write("                                   Truyền thống đêm giao thừa đã trở lại thành phố New York khi người dân có thể chào đón năm mới với hoa giấy, tiếng hò reo và quả cầu pha lê được thả xuống ở Quảng trường Thời đại.\r\n");
      out.write("                               </strong>\r\n");
      out.write("                            </h2>\r\n");
      out.write("                            <p class=\"category-desc my-4\">\r\n");
      out.write("                                Hàng nghìn người đứng kề vai nhau để chứng kiến ​​quả cầu nặng 6 tấn, nạm gần 2.700 viên pha lê Waterford, được thả xuống ở Quảng trường Thời đại.\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"category-desc\">\r\n");
      out.write("                                Buổi lễ có sự tham dự của khoảng 15.000 khán giả trực tiếp - ít hơn nhiều so với hàng chục nghìn người thường đổ về quảng trường để đắm mình trong ánh đèn và tiếng hò reo của đêm giao thừa thường niên, theo AP.</p>\r\n");
      out.write("                                <div class=\"category-img\">\r\n");
      out.write("                                    <img src=\"./img/newyourk.webp\" alt=\"\">\r\n");
      out.write("                                    <span class=\"img-desc\">Truyền thống đón năm mới của New York đã quay trở lại. Ảnh: AP</span>\r\n");
      out.write("                             <p class=\"category-desc mt-4\">Sự kiện được cử hành khi Mỹ lạc quan rằng những ngày tồi tệ nhất của đại dịch đang ở phía sau. Lễ thả quả cầu năm ngoái đã không thể chào đón công chúng do dịch bệnh.</p>  \r\n");
      out.write("\r\n");
      out.write("                             <p class=\"category-desc mt-4\">Giới chức yêu cầu những người tham dự phải đeo khẩu trang và xuất trình bằng chứng đã tiêm chủng. Ban tổ chức lúc đầu dự kiến rằng hơn 50.000 người có thể tham gia, nhưng kế hoạch đã bị thu hẹp đáng kể vì tình trạng lây nhiễm lan rộng.</p>  \r\n");
      out.write("\r\n");
      out.write("                                <p class=\"category-desc mt-4\">“Tôi rất vui khi năm 2021 đã kết thúc vì nó gây ra rất nhiều vấn đề cho mọi người\", Mary Gonzalez, một người tham dự đến từ thành phố Mexico, cho biết. “Chúng tôi hy vọng rằng năm 2022 sẽ tốt hơn nhiều so với năm nay\".</p>  \r\n");
      out.write("\r\n");
      out.write("                                    <p class=\"category-desc mt-4\">Lễ thả quả cầu hàng năm diễn ra khi đồng hồ điểm lúc nửa đêm và mở ra năm mới. Nhà chức trách New York nhất quyết tổ chức sự kiện đêm giao thừa để chứng minh khả năng phục hồi của thành phố, ngay cả trong bối cảnh dịch Covid-19 đang bùng phát trở lại.</p>  \r\n");
      out.write("                                    <div class=\"category-img\">\r\n");
      out.write("                                        <img src=\"./img/newyourk2.webp\" alt=\"\">\r\n");
      out.write("                                        <span class=\"img-desc\">Sự kiện được cử hành khi Mỹ lạc quan rằng những ngày tồi tệ nhất của đại dịch đang ở phía sau. Ảnh: New York Times.</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  <p class=\"category-desc mt-4\">Thành phố New York đã báo cáo số ca nhiễm kỷ lục trước thềm năm mới, với gần 44.000 trường hợp vào ngày 29/12/2021, theo số liệu của bang New York.</p>  \r\n");
      out.write("\r\n");
      out.write("                                  <p class=\"category-desc mt-4\">Eric Adams, thị trưởng kế nhiệm của New York, đã tuyên thệ nhậm chức tại Quảng trường Thời đại, ngay sau khi quả cầu được thả xuống.</p>  \r\n");
      out.write("\r\n");
      out.write("                                    <p class=\"category-desc mt-4\">“Thật tuyệt khi New York cho cả nước thấy cách chúng tôi quay trở lại”, ông cho biết.</p>  \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"ab mt-5\"></span>\r\n");
      out.write("                        <div class=\"hero mt-5 mb-5\">\r\n");
      out.write("                            <h2 class=\"hero-title\"><strong>Bài liên quan</strong></h2>\r\n");
      out.write("                            <div class=\"hero-content  d-flex gap-3\">\r\n");
      out.write("                            <div class=\"hero-img col-sm-12 col-lg-4 col-md-4\">\r\n");
      out.write("                                <img src=\"./img/covid.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                                <div  class=\" col-lg-8\">\r\n");
      out.write("                                    <a href=\"#!\" class=\"hero-name \"id=\"news-title\"><strong>Nỗi dằn vặt của những người mắc Covid-19 dù đã tiêm vaccine đầy đủ</strong></a>\r\n");
      out.write("                                    <p class=\"hero-desc\">Khi biết mình mắc Covid-19 vào tháng 11, Sean Williams, 50 tuổi, sống tại New York (Mỹ), cảm thấy rất tội lỗi và tủi hổ. Con gái anh, 14 tuổi, cũng dương tính với nCoV.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"hero-content d-flex gap-3 mt-5\">\r\n");
      out.write("                            <div class=\"hero-img col-lg-4 col-md-4\">\r\n");
      out.write("                                <img src=\"./img/usa.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <a href=\"#!\" class=\"hero-name \"id=\"news-title\"><strong>Diễn biến dịch bất thường ở New York vì biến chủng Omicron</strong></a>\r\n");
      out.write("                                <p class=\"hero-desc\">Số trẻ em nhập viện vì Covid-19 ở New York tăng gấp 4 lần giữa lúc Mỹ ghi nhận mức trung bình ca nhiễm trong 7 ngày cao nhất kể từ tháng một trong bối cảnh Omicron lấn át Delta.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"tag-hot mt-5\">\r\n");
      out.write("                            <div class=\"container d-lg-flex justify-content-start align-items-center tag-slide\">\r\n");
      out.write("                                <i class=\"fas fa-tags text-secondary icon-tag\"></i>\r\n");
      out.write("                              \r\n");
      out.write("                                <a class=\"tag-hot_name\"># Số liệu Covid-19</a>\r\n");
      out.write("                                <a class=\"tag-hot_name\"># Biến chủng Omicron</a>\r\n");
      out.write("                                <a class=\"tag-hot_name\"># Hello World</a>\r\n");
      out.write("                                <i class=\"fas fa-plus-circle text-secondary icon-tag\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("</div>\r\n");
      out.write("                 <div class=\"col-md-4 col-lg-4 layout-content-right_news\">\r\n");
      out.write("                     <h2 class=\"content-right_title mb-3 \">Đọc tiếp</h2>\r\n");
      out.write("                     <div class=\"content-right_news d-flex gap-3\">\r\n");
      out.write("                        <img src=\"./img/elon-musk.webp\" alt=\"\" class=\"content-right_news-img \">\r\n");
      out.write("                        <a href=\"\" class=\"content-right_news-title\" id=\"news-title\">\r\n");
      out.write("                           <strong>Vị tỉ phú giaù nhất thế giới hiện tại.</strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"content-right_news  d-lg-flex  gap-3 mt-4\">\r\n");
      out.write("                        <img src=\"./img/hoa dao.webp\" alt=\"\" class=\"content-right_news-img\">\r\n");
      out.write("                        <a href=\"\" class=\"content-right_news-title\" id=\"news-title\">\r\n");
      out.write("                            <strong>Nông dân Miền Bắc đang tập trung chăm đào.</strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"content-right_news  d-flex gap-3 mt-4\" >\r\n");
      out.write("                        <img src=\"./img/taliban.webp\" alt=\"\" class=\"content-right_news-img \">\r\n");
      out.write("                        <a href=\"\" class=\"content-right_news-title\" id=\"news-title\">\r\n");
      out.write("                           <strong>Taliban đổ bỏ 3.000 lít rượu xuống con kênh ở Kabul</strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"content-right_news d-flex gap-3 mt-4\">\r\n");
      out.write("                        <img src=\"./img/tq.webp\" alt=\"\" class=\"content-right_news-img \">\r\n");
      out.write("                        <a href=\"\" class=\"content-right_news-title\" id=\"news-title\">\r\n");
      out.write("                           <strong>Trung Quốc khẩn trương tiếp tế cho 13 triệu dân bị phong tỏa</strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content featrue layout-container\">\r\n");
      out.write("        <div class=\"container mt-xxl-5\">\r\n");
      out.write("            <h2 class=\"featrue-title\"><strong>BẠN CÓ THỂ QUAN TÂM</strong></h2>\r\n");
      out.write("            <div class=\"d-flex\">\r\n");
      out.write("            <div class=\"col-lg-8\">\r\n");
      out.write("                <div class=\"hero-content d-flex gap-3 mt-5\">\r\n");
      out.write("                    <div class=\"hero-img col-lg-4 col-md-4\">\r\n");
      out.write("                        <img src=\"./img/who.webp\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-8\">\r\n");
      out.write("                        <a href=\"#!\" class=\"featrue-name \"id=\"news-title\"><strong>Tổng giám đốc WHO: Đại dịch có thể chấm dứt trong năm 2022</strong></a>\r\n");
      out.write("                        <p class=\"featrue-desc\">WHO sẽ hợp tác với các chính phủ để ưu tiên chuyển vaccine cho những định chế như COVAX và AVAT, với mục tiêu tiêm ngừa Covid-19 cho 70% dân số toàn cầu vào giữa năm 2022.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"hero-content d-flex gap-3 mt-5\">\r\n");
      out.write("                        <div class=\"hero-img col-lg-4 col-md-4\">\r\n");
      out.write("                            <img src=\"./img/nga.webp\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-8\">\r\n");
      out.write("                            <a href=\"#!\" class=\"featrue-name \"id=\"news-title\"><strong>\r\n");
      out.write("                                Nga cảnh báo về 'đường lối gây hấn' của phương Tây</strong></a>\r\n");
      out.write("                            <p class=\"featrue-desc\">Ngoại trưởng Nga nói rằng Moscow có thể bị buộc phải “loại bỏ các mối đe dọa không thể chấp nhận được đối với an ninh của chúng tôi”.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hero-content d-flex gap-3 mt-5\">\r\n");
      out.write("                            <div class=\"hero-img col-lg-4 col-md-4\">\r\n");
      out.write("                                <img src=\"./img/name.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <a href=\"#!\" class=\"featrue-name \"id=\"news-title\"><strong>Vụ án bé trai 6 tuổi bị cha và mẹ kế sát hại gây rúng động ở Anh</strong></a>\r\n");
      out.write("                                <p class=\"featrue-desc\">Người dân Anh đang yêu cầu tòa án trừng phạt cặp vợ chồng sát hại con trai 6 tuổi với bản án nghiêm khắc hơn, khi cho rằng án tù tổng cộng 50 năm là chưa thỏa đáng..</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"hero-content d-flex gap-3 mt-5\">\r\n");
      out.write("                                <div class=\"hero-img col-lg-4 col-md-4\">\r\n");
      out.write("                                    <img src=\"./img/usa.webp\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                  <a href=\"#!\" class=\"featrue-name \"id=\"news-title\"><strong>Diễn biến dịch bất thường ở New York vì biến chủng Omicron</strong></a>\r\n");
      out.write("                                    <p class=\"featrue-desc\">Số trẻ em nhập viện vì Covid-19 ở New York tăng gấp 4 lần giữa lúc Mỹ ghi nhận mức trung bình ca nhiễm trong 7 ngày cao nhất kể từ tháng một trong bối cảnh Omicron lấn át Delta.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"hero-content d-flex gap-3 mt-5\">\r\n");
      out.write("                                    <div class=\"hero-img col-lg-4 col-md-4\">\r\n");
      out.write("                                        <img src=\"./img/suc khoe.webp\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                        <a href=\"#!\" class=\"featrue-name\"id=\"news-title\"><strong>\r\n");
      out.write("                                            Thực phẩm thay thế giúp dân văn phòng kiểm soát cân nặng</strong></a>\r\n");
      out.write("                                        <p class=\"featrue-desc\">Bên cạnh rèn luyện thể chất, chế độ dinh dưỡng ít calo nhưng đủ dinh dưỡng cũng góp phần không nhỏ giúp kiểm soát cân nặng.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>   \r\n");
      out.write("\r\n");
      out.write("                   <h2 class=\"featrue-title-desc mt-5\"><strong>XEM THÊM</strong></h2>\r\n");
      out.write("                   <div class=\"hero-content d-flex gap-3 mt-5\">\r\n");
      out.write("                    <div class=\"hero-img col-lg-4 col-md-4\">\r\n");
      out.write("                        <img src=\"./img/france.webp\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-8\">\r\n");
      out.write("                        <a href=\"#!\" class=\"featrue-name \" id=\"news-title\"><strong>Quốc hội Pháp dừng họp vì phát biểu của Tổng thống Macron</strong></a>\r\n");
      out.write("                        <p class=\"featrue-desc\">Quốc hội Pháp hôm 5/1 quyết định dừng thảo luận về đạo luật đối phó với Covid-19 sau khi Tổng thống Emmanuel Macron tuyên bố ông muốn “chọc giận” những người chưa tiêm chủng.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"hero-content d-flex gap-3 mt-5\">\r\n");
      out.write("                        <div class=\"hero-img col-lg-4 col-md-4\">\r\n");
      out.write("                            <img src=\"./img/coin.webp\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-8\">\r\n");
      out.write("                            <a href=\"#!\" class=\"featrue-name \"id=\"news-title\"><strong>Binance đầu tư vào startup blockchain của Việt Nam</strong></a>\r\n");
      out.write("                            <p class=\"featrue-desc\">Sáng 5/1, quỹ đầu tư Binance Labs thông báo rót vốn vào Coin98. Đây là nền tảng tài chính phi tập trung (DeFi) với các sản phẩm như ví không lưu ký Coin98 Wallet, sàn giao dịch phi tập trung Coin98 Exchange và cổng giao dịch đa chuỗi Space Gate.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hero-content d-flex gap-3 mt-5\">\r\n");
      out.write("                            <div class=\"hero-img col-lg-4 col-md-4\">\r\n");
      out.write("                                <img src=\"./img/bird.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <a href=\"#!\" class=\"featrue-name \"id=\"news-title\"><strong>Máy bay Vietnam Airlines bị dọa bắn hạ trên vịnh Tokyo</strong></a>\r\n");
      out.write("                                <p class=\"featrue-desc\">Cục Hàng không Việt Nam vừa thông báo vụ việc máy bay của hãng hàng không Vietnam Airlines bị đe dọa bắn hạ trên hành trình từ Nhật Bản về Việt Nam.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>   \r\n");
      out.write("                        <div class=\"hero-content d-flex gap-3 mt-5\">\r\n");
      out.write("                            <div class=\"hero-img col-lg-4 col-md-4\">\r\n");
      out.write("                                <img src=\"./img/usa.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <a href=\"#!\" class=\"featrue-name \"id=\"news-title\"><strong>Diễn biến dịch bất thường ở New York vì biến chủng Omicron</strong></a>\r\n");
      out.write("                                <p class=\"featrue-desc\">Số trẻ em nhập viện vì Covid-19 ở New York tăng gấp 4 lần giữa lúc Mỹ ghi nhận mức trung bình ca nhiễm trong 7 ngày cao nhất kể từ tháng một trong bối cảnh Omicron lấn át Delta.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"./js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
