/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-02 08:09:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Bách Khoa News</title>\r\n");
      out.write("    <!-- Icon Boostrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css\">\r\n");
      out.write("    <!-- Link Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- OWL -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!--Font Awesome --> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\" integrity=\"sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <!-- CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/shared.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/responsive.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Tag hot -->\r\n");
      out.write("        <div class=\"tag-hot \">\r\n");
      out.write("            <div class=\"container d-none d-lg-flex justify-content-start align-items-center\">\r\n");
      out.write("                <i class=\"far fa-arrow-alt-circle-right tag-hot_icon\"></i>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"tag-hot_name\">Số liệu Covid-19</div>\r\n");
      out.write("                <div class=\"tag-hot_name\">Biến chủng Omicron</div>\r\n");
      out.write("                <div class=\"tag-hot_name\">Best Choice Award</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Content -->\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"content-hot d-flex\">\r\n");
      out.write("                    <div class=\"col-lg-4 d-none d-lg-block\">\r\n");
      out.write("                        <div class=\"content-left_news d-flex\">\r\n");
      out.write("                            <img src=\"./img/Trang_xau_2.webp\" alt=\"\" class=\"content-left_news-img\">\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"content-left_news-title\">\r\n");
      out.write("                                Doctor Strange ác quỷ tái xuất trong 'Multiverse of Madness\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"content-left_news d-flex\">\r\n");
      out.write("                            <img src=\"./img/Trang_xau_2.webp\" alt=\"\" class=\"content-left_news-img\">\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"content-left_news-title\">\r\n");
      out.write("                                Doctor Strange ác quỷ tái xuất trong 'Multiverse of Madness\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"content-left_news d-flex\">\r\n");
      out.write("                            <img src=\"./img/Trang_xau_2.webp\" alt=\"\" class=\"content-left_news-img\">\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"content-left_news-title\">\r\n");
      out.write("                                Doctor Strange ác quỷ tái xuất trong 'Multiverse of Madness\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"content-left_news d-flex\">\r\n");
      out.write("                            <img src=\"./img/Trang_xau_2.webp\" alt=\"\" class=\"content-left_news-img\">\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"content-left_news-title\">\r\n");
      out.write("                                Doctor Strange ác quỷ tái xuất trong 'Multiverse of Madness\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"content-left_news d-flex\">\r\n");
      out.write("                            <img src=\"./img/Trang_xau_2.webp\" alt=\"\" class=\"content-left_news-img\">\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"content-left_news-title\">\r\n");
      out.write("                                Doctor Strange ác quỷ tái xuất trong 'Multiverse of Madness\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-8 d-md-flex \">\r\n");
      out.write("                        <div class=\"col-lg-8 col-xs-12\">\r\n");
      out.write("                            <div class=\"content-main_news\">\r\n");
      out.write("                                <img src=\"./img/main-news.webp\" alt=\"\" class=\"content-main_news-img\">\r\n");
      out.write("                                <h1 class=\"content-main_news-title\" id=\"news-title\">F0 ở Hà Nội phải tự chữa bệnh vì gọi y tế phường nhưng không ai đến</h1>\r\n");
      out.write("                                <div class=\"content-main_news-text\">\r\n");
      out.write("                                    Khi có kết quả dương tính với nCoV, anh Nguyễn Văn Khải gọi điện cho trung tâm y tế phường để khai báo nhưng một tuần sau đó, không có nhân viên nào đến cấp phát thuốc.\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <a href=\"\" id=\"news-title\" class=\"content-left_news-title\">Hà Nội ghi nhận thêm 1622 ca mắc Covid-19 mới</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-4 col-xs-12\">\r\n");
      out.write("                            <div class=\"content-right_news\">\r\n");
      out.write("                                <img src=\"./img/quynhdanh6.webp\" alt=\"\" class=\"content-right_news-img\">\r\n");
      out.write("                                <a href=\"\" class=\"content-right_news-title\" id=\"news-title\">\r\n");
      out.write("                                    TP.HCM sẽ tăng cấp độ dịch các địa bàn không chăm sóc tốt F0 tại nhà\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"content-right_news\">\r\n");
      out.write("                                <img src=\"./img/quynhdanh6.webp\" alt=\"\" class=\"content-right_news-img\">\r\n");
      out.write("                                <a href=\"\" class=\"content-right_news-title\" id=\"news-title\">\r\n");
      out.write("                                    TP.HCM sẽ tăng cấp độ dịch các địa bàn không chăm sóc tốt F0 tại nhà\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Multimedia -->\r\n");
      out.write("                <div class=\"multimedia\">\r\n");
      out.write("                    <div class=\"multimedia-header d-flex\">\r\n");
      out.write("                        <div class=\"multimedia-title\">Multimedia</div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"multimedia-nav\">\r\n");
      out.write("                            <ul class=\"multimedia-nav_list d-md-flex d-none\">\r\n");
      out.write("                                <li class=\"multimedia-nav_item\">\r\n");
      out.write("                                    <a href=\"\" class=\"multimedia-nav_link\">Video</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"multimedia-nav_item\">\r\n");
      out.write("                                    <a href=\"\" class=\"multimedia-nav_link\">Longform</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"multimedia-nav_item\">\r\n");
      out.write("                                    <a href=\"\" class=\"multimedia-nav_link\">Voices</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"multimedia-nav_item\">\r\n");
      out.write("                                    <a href=\"\" class=\"multimedia-nav_link\">Lens</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"multimedia-nav_item\">\r\n");
      out.write("                                    <a href=\"\" class=\"multimedia-nav_link\">Story</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"multimedia-nav_item\">\r\n");
      out.write("                                    <a href=\"\" class=\"multimedia-nav_link\">Quizz</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"multimedia-content d-lg-flex\">\r\n");
      out.write("                        <div class=\"col-lg-6 col-12\">\r\n");
      out.write("                            <img src=\"./img/banh-kem.webp\" alt=\"\" class=\"multimedia-content_news-img\">\r\n");
      out.write("                            <h1 class=\"multimedia-content_news-title\" id=\"multimedia-title\">Lớp làm bánh kem dịp Giáng sinh ở TP.HCM</h1>\r\n");
      out.write("                            <div class=\"multimedia-content_news-text\">\r\n");
      out.write("                                Trải qua 3 tiếng tỉ mẩn làm từng khâu theo hướng dẫn, tôi cũng hoàn thành chiếc bánh kem đầu tiên trong đời. Tôi dự định mang thành phẩm đến bữa tiệc Giáng sinh cùng bạn bè.\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 col-12 multimedia-right d-flex flex-wrap\">\r\n");
      out.write("                            <div class=\"col-lg-6 col-6 multimedia-right_news\">\r\n");
      out.write("                                <img src=\"./img/jun-vu.webp\" alt=\"\" class=\"content-right_news-img\">\r\n");
      out.write("                                <a href=\"\" class=\"content-right_news-title\" id=\"multimedia-title\">\r\n");
      out.write("                                    Jun Vũ và dàn người đẹp diện đầm xuyên thấu trên sàn diễn\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-6 col-6 multimedia-right_news\">\r\n");
      out.write("                                <img src=\"./img/jun-vu.webp\" alt=\"\" class=\"content-right_news-img\">\r\n");
      out.write("                                <a href=\"\" class=\"content-right_news-title\" id=\"multimedia-title\">\r\n");
      out.write("                                    Jun Vũ và dàn người đẹp diện đầm xuyên thấu trên sàn diễn\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-6 col-6 multimedia-right_news\">\r\n");
      out.write("                                <img src=\"./img/jun-vu.webp\" alt=\"\" class=\"content-right_news-img\">\r\n");
      out.write("                                <a href=\"\" class=\"content-right_news-title\" id=\"multimedia-title\">\r\n");
      out.write("                                    Jun Vũ và dàn người đẹp diện đầm xuyên thấu trên sàn diễn\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-6 col-6 multimedia-right_news\">\r\n");
      out.write("                                <img src=\"./img/jun-vu.webp\" alt=\"\" class=\"content-right_news-img\">\r\n");
      out.write("                                <a href=\"\" class=\"content-right_news-title\" id=\"multimedia-title\">\r\n");
      out.write("                                    Jun Vũ và dàn người đẹp diện đầm xuyên thấu trên sàn diễn\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Books -->\r\n");
      out.write("                <div class=\"books\">\r\n");
      out.write("                    <div class=\"books-header\">\r\n");
      out.write("                        <h1 class=\"books-title\">Books</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"books-content owl-carousel owl-theme \">\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"books-content_img\">\r\n");
      out.write("                                <img src=\"./img/nxb_th.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"\" class=\"books-content_title\" id=\"news-title\">Những nét đặc sắc trong văn hóa tiếng Việt</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"books-content_img\">\r\n");
      out.write("                                <img src=\"./img/nxb_th.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"\" class=\"books-content_title\" id=\"news-title\">Những nét đặc sắc trong văn hóa tiếng Việt</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"books-content_img\">\r\n");
      out.write("                                <img src=\"./img/nxb_th.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"\" class=\"books-content_title\" id=\"news-title\">Những nét đặc sắc trong văn hóa tiếng Việt</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"books-content_img\">\r\n");
      out.write("                                <img src=\"./img/nxb_th.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"\" class=\"books-content_title\" id=\"news-title\">Những nét đặc sắc trong văn hóa tiếng Việt</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"books-content_img\">\r\n");
      out.write("                                <img src=\"./img/nxb_th.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"\" class=\"books-content_title\" id=\"news-title\">Những nét đặc sắc trong văn hóa tiếng Việt</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"books-content_img\">\r\n");
      out.write("                                <img src=\"./img/nxb_th.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"\" class=\"books-content_title\" id=\"news-title\">Những nét đặc sắc trong văn hóa tiếng Việt</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"books-content_img\">\r\n");
      out.write("                                <img src=\"./img/nxb_th.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"\" class=\"books-content_title\" id=\"news-title\">Những nét đặc sắc trong văn hóa tiếng Việt</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"books-content_img\">\r\n");
      out.write("                                <img src=\"./img/nxb_th.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"\" class=\"books-content_title\" id=\"news-title\">Những nét đặc sắc trong văn hóa tiếng Việt</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"books-content_img\">\r\n");
      out.write("                                <img src=\"./img/nxb_th.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"\" class=\"books-content_title\" id=\"news-title\">Những nét đặc sắc trong văn hóa tiếng Việt</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"books-content_img\">\r\n");
      out.write("                                <img src=\"./img/nxb_th.webp\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"\" class=\"books-content_title\" id=\"news-title\">Những nét đặc sắc trong văn hóa tiếng Việt</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- News Category -->\r\n");
      out.write("                <div class=\"news-category d-flex flex-wrap\">\r\n");
      out.write("                    <div class=\"col-lg-3 col-6 news-category_wrap\">\r\n");
      out.write("                        <div class=\"news-category_header\">Xuất Bản</div>\r\n");
      out.write("                        <img src=\"./img/caterory.webp\" alt=\"\" class=\"news-category_img d-lg-block d-none\">    \r\n");
      out.write("                        <a href=\"\" id=\"news-title\" class=\"news-category_title d-lg-block d-none\">Công trình nghiên cứu ý nghĩa thế giới</a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 col-6 news-category_wrap\">\r\n");
      out.write("                        <div class=\"news-category_header\">Xuất Bản</div>\r\n");
      out.write("                        <img src=\"./img/caterory.webp\" alt=\"\" class=\"news-category_img d-lg-block d-none\">    \r\n");
      out.write("                        <a href=\"\" id=\"news-title\" class=\"news-category_title d-lg-block d-none\">Công trình nghiên cứu ý nghĩa thế giới</a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 col-6 news-category_wrap\">\r\n");
      out.write("                        <div class=\"news-category_header\">Xuất Bản</div>\r\n");
      out.write("                        <img src=\"./img/caterory.webp\" alt=\"\" class=\"news-category_img d-lg-block d-none\">    \r\n");
      out.write("                        <a href=\"\" id=\"news-title\" class=\"news-category_title d-lg-block d-none\">Công trình nghiên cứu ý nghĩa thế giới</a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 col-6 news-category_wrap\">\r\n");
      out.write("                        <div class=\"news-category_header\">Xuất Bản</div>\r\n");
      out.write("                        <img src=\"./img/caterory.webp\" alt=\"\" class=\"news-category_img d-lg-block d-none\">    \r\n");
      out.write("                        <a href=\"\" id=\"news-title\" class=\"news-category_title d-lg-block d-none\">Công trình nghiên cứu ý nghĩa thế giới</a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 col-6 news-category_wrap\">\r\n");
      out.write("                        <div class=\"news-category_header\">Xuất Bản</div>\r\n");
      out.write("                        <img src=\"./img/caterory.webp\" alt=\"\" class=\"news-category_img d-lg-block d-none\">    \r\n");
      out.write("                        <a href=\"\" id=\"news-title\" class=\"news-category_title d-lg-block d-none\">Công trình nghiên cứu ý nghĩa thế giới</a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 col-6 news-category_wrap\">\r\n");
      out.write("                        <div class=\"news-category_header\">Xuất Bản</div>\r\n");
      out.write("                        <img src=\"./img/caterory.webp\" alt=\"\" class=\"news-category_img d-lg-block d-none\">    \r\n");
      out.write("                        <a href=\"\" id=\"news-title\" class=\"news-category_title d-lg-block d-none\">Công trình nghiên cứu ý nghĩa thế giới</a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 col-6 news-category_wrap\">\r\n");
      out.write("                        <div class=\"news-category_header\">Xuất Bản</div>\r\n");
      out.write("                        <img src=\"./img/caterory.webp\" alt=\"\" class=\"news-category_img d-lg-block d-none\">    \r\n");
      out.write("                        <a href=\"\" id=\"news-title\" class=\"news-category_title d-lg-block d-none\">Công trình nghiên cứu ý nghĩa thế giới</a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 col-6 news-category_wrap\">\r\n");
      out.write("                        <div class=\"news-category_header\">Xuất Bản</div>\r\n");
      out.write("                        <img src=\"./img/caterory.webp\" alt=\"\" class=\"news-category_img d-lg-block d-none\">    \r\n");
      out.write("                        <a href=\"\" id=\"news-title\" class=\"news-category_title d-lg-block d-none\">Công trình nghiên cứu ý nghĩa thế giới</a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"news-fast d-flex\">\r\n");
      out.write("                            <a href=\"\"><img src=\"./img/dai_tuong_vo_nguyen_giap.webp\" alt=\"\" class=\"news-fast_img\"></a>\r\n");
      out.write("                            <a href=\"\" id=\"news-title\" class=\"news-fast_title\">Triển lãm thơ về Đại Tướng Võ Nguyên Giáp</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"magazine\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"magazine-header\">magazine</div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-6 col-lg-3 magazine_wrap\">\r\n");
      out.write("                        <div class=\"magazine_img\">\r\n");
      out.write("                            <img src=\"./img/thumb_story.webp\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"magazine_type\">Story</div>\r\n");
      out.write("                        <div class=\"magazine_title\">24 giờ ‘bình thường mới’ rảnh rang nhờ  công nghệ</div>\r\n");
      out.write("                        <div class=\"magazine_icon\">\r\n");
      out.write("                            <i class=\"bi bi-bookmarks\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-6 col-lg-3 magazine_wrap\">\r\n");
      out.write("                        <div class=\"magazine_img\">\r\n");
      out.write("                            <img src=\"./img/thumb_story.webp\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"magazine_type\">Story</div>\r\n");
      out.write("                        <div class=\"magazine_title\">24 giờ ‘bình thường mới’ rảnh rang nhờ  công nghệ</div>\r\n");
      out.write("                        <div class=\"magazine_icon\">\r\n");
      out.write("                            <i class=\"bi bi-bookmarks\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-6 col-lg-3 magazine_wrap\">\r\n");
      out.write("                        <div class=\"magazine_img\">\r\n");
      out.write("                            <img src=\"./img/thumb_story.webp\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"magazine_type\">Story</div>\r\n");
      out.write("                        <div class=\"magazine_title\">24 giờ ‘bình thường mới’ rảnh rang nhờ  công nghệ</div>\r\n");
      out.write("                        <div class=\"magazine_icon\">\r\n");
      out.write("                            <i class=\"bi bi-bookmarks\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-6 col-lg-3 magazine_wrap\">\r\n");
      out.write("                        <div class=\"magazine_img\">\r\n");
      out.write("                            <img src=\"./img/thumb_story.webp\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"magazine_type\">Story</div>\r\n");
      out.write("                        <div class=\"magazine_title\">24 giờ ‘bình thường mới’ rảnh rang nhờ  công nghệ</div>\r\n");
      out.write("                        <div class=\"magazine_icon\">\r\n");
      out.write("                            <i class=\"bi bi-bookmarks\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\"> </script>\r\n");
      out.write("    <script src=\"./js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./js/main.js\"></script>\r\n");
      out.write(" 	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
