/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-11 17:38:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class introduce_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Giới thiệu</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css\">\r\n");
      out.write("    <!-- Link Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--Font Awesome --> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\" integrity=\"sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <!-- CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/shared.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/responsive.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/introduce.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	   <div class=\"content-introduce\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"d-flex flex-wrap\">\r\n");
      out.write("                <div class=\"col-md-6 col-12\">\r\n");
      out.write("                    <div class=\"content-introduce_header\">\r\n");
      out.write("                        <h1>Bách Khoa News là:</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"content-introduce_wrap\">\r\n");
      out.write("                        <div class=\"content-introduce_text\">\r\n");
      out.write("                            <b>Bách Khoa New</b> được xây dựng dựa trên tiêu chí là cổng thông tin khổng lồ và hoàn toàn miễn phí về các vấn đề xã hội, chính trị … Tất cả những thông tin tại Bách Khoa New  được sưu tầm và tham khảo từ nhiều nguồn khác nhau có chọn lọc, thông tin là hoàn toàn chính xác và luôn là những tin tức mới nhất.\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"content-introduce_text\">\r\n");
      out.write("                            <a href=\"\">Bách Khoa News</a> còn là nơi kết nối, truyền tải thông tin từ khắp mọi nơi trên thế giới giúp bạn đọc luôn cập nhập được mọi thông tin ở mọi lĩnh vực không những vậy Bách Khoa News còn là một kho giải chí cực lớn với những câu chuyện đặc sắc trong cuộc sống hang ngày và page luôn luôn cập nhập những thông tin mới nhất để phục vụ quý đọc giả.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-12\">\r\n");
      out.write("                    <img src=\"./img/about-us.png\" alt=\"\" class=\"content-introduce_img\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"d-flex flex-wrap\">\r\n");
      out.write("                <div class=\"col-md-6 col-12\">\r\n");
      out.write("                    <div class=\"content-introduce_title\">Sứ mệnh</div>\r\n");
      out.write("                    <div class=\"content-introduce_text\">\r\n");
      out.write("                        Sứ mệnh của chúng tôi là mang đến cho độc giả, những người người mang lại động lực cho chúng tôi thực hiện dự  án  <b>Bách Khoa News</b> New này nhưng thông tin hay và bổ ích. \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"content-introduce_text\">\r\n");
      out.write("                        <b>Bách Khoa News</b> cam kết mang lại cho độc giả một trải nghiệm tốt nhất sau những ngày dài làm việc mệt mỏi. Bách Khoa News sẽ luôn đồng hành cùng với mọi người và sẽ luôn cùng những đọc giả thân yêu xan sẻ những niềm vui trong cuộc sống.\r\n");
      out.write("					</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-12\">\r\n");
      out.write("                    <div class=\"content-introduce_title\">Tầm nhìn</div>\r\n");
      out.write("                    <div class=\"content-introduce_text\">\r\n");
      out.write("                        Chúng tôi mong muốn <b>Bách Khoa News</b> sẽ trở thành địa chỉ tìm kiếm thông tin đáng tin cậy cho tất cả mọi người. Quan trong hơn Bách khoa New sẽ luôn là người bạn cũng như một công cự tuyệt vời để mọi người cập nhập tin tức.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"content-introduce_text\">\r\n");
      out.write("                        Chúng tôi sẽ không ngừng nỗ lực và phát triển, phủ rộng thông tin đến mọi miền đất nước, đến những nơi cần chúng tôi.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"d-flex flex-wrap\">\r\n");
      out.write("                <div class=\"col-md-6 col-12\">\r\n");
      out.write("                    <div class=\"content-introduce_title\">Thành viên Đội Ngũ</div>\r\n");
      out.write("                    <div class=\"content-introduce_text\">\r\n");
      out.write("                        Trưởng nhóm: Nguyễn Duy Khánh <br>\r\n");
      out.write("                        Thành viên: Hồ Cảnh Quang <br>\r\n");
      out.write("                        Trần Xuân Bắc <br>\r\n");
      out.write("                        Phạm Đức Quân <br>\r\n");
      out.write("                        Đàm Quốc Uy <br>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-6 col-12\">\r\n");
      out.write("                    <div class=\"content-introduce_text\">\r\n");
      out.write("                        <b>Bách Khoa News</b> chúc tất cả đọc giả yêu quý có một ngày tuyệt vời và cảm ơn quý vị đã ghé thăm và ủng hộ chúng tôi !\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	 <script src=\"./js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"./js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
